/* Auto‑generated by scripts/generate-book-data.js – DO NOT EDIT */
window.BOOK_DATA = {
  "title": "Basics",
  "chapters": [
    {
      "href": "deep-learning-crash-course.html",
      "title": "Deep Learning Crash Course"
    }
  ]
};