/* Auto‑generated by scripts/generate-book-data.js – DO NOT EDIT */
window.BOOK_DATA = {
  "title": "Training Research",
  "chapters": [
    {
      "href": "lora_fine_tuning.html",
      "title": "Lora_fine_tuning"
    }
  ]
};