/* Auto‑generated by scripts/generate-book-data.js – DO NOT EDIT */
window.BOOK_DATA = {
  "title": "Algorithms",
  "chapters": [
    {
      "href": "00-prologue.html",
      "title": "0. Prologue"
    },
    {
      "href": "01-algorithms-with-numbers.html",
      "title": "1. Algorithms With Numbers"
    },
    {
      "href": "04-paths-in-graphs.html",
      "title": "4. Paths In Graphs"
    },
    {
      "href": "05-greedy-algorithms.html",
      "title": "5. Greedy Algorithms"
    },
    {
      "href": "06-dynamic-programming.html",
      "title": "6. Dynamic Programming"
    },
    {
      "href": "07-linear-programming.html",
      "title": "7. Linear Programming"
    }
  ]
};