/* Auto‑generated by scripts/generate-book-data.js – DO NOT EDIT */
window.BOOK_DATA = {
  "title": "Pattern Classification",
  "chapters": [
    {
      "href": "01-introduction.html",
      "title": "1. Introduction"
    },
    {
      "href": "02-bayes-decision-theory.html",
      "title": "2. Bayes Decision Theory"
    }
  ]
};