/* Auto‑generated by scripts/generate-book-data.js – DO NOT EDIT */
window.BOOK_DATA = {
  "title": "In Simple Terms",
  "chapters": [
    {
      "href": "cross_entropy_gradient.html",
      "title": "Cross_entropy_gradient"
    }
  ]
};